{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-refresh-healer.fullname" . }}
  labels:
    {{- include "es-refresh-healer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "es-refresh-healer.selectorLabels" . | nindent 4 }}
{{- end }}

