{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "es-refresh-healer.fullname" . }}
  labels:
    {{- include "es-refresh-healer.labels" . | nindent 4 }}
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "es-refresh-healer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}

